### ISSUE TITLE
Help with your project

### ISSUE THREAD

**Issue by ebebbington** [ramonmedeiros/learning_deno#1]
Hey, i've seen your posts about problems with Drash and writing tests for your drash server. i'm one of the maintainers of Drash, and if you'd like, you can pop by the discord and ask for any help or queries: https://discord.gg/avuyS4

**Comment by ramonmedeiros** [comment]
Wow, thanks so much for your help.

I recently moved to `opine`. But I just started to use `Rhum`. May soon I will switch to Drash

Thanks for the attention

**Comment by ebebbington** [comment]
No problem :) Just wanted to let you know as I know what it's like to either not know where to ask for help, or not get any 👍
